# Generated by Django 4.2.14 on 2026-07-23 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumnus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "date_of_birth_bs",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Date of birth (B.S.)"
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("computer", "Computer Engineering"),
                            ("electronics", "Electronics & Communication Engineering"),
                            ("electrical", "Electrical Engineering"),
                            ("civil", "Civil Engineering"),
                            ("mechanical", "Mechanical Engineering"),
                            ("architecture", "Architecture"),
                            ("aerospace", "Aerospace Engineering"),
                            ("chemical", "Chemical & Applied Sciences"),
                            ("science_humanities", "Science & Humanities"),
                            ("other", "Other / Interdisciplinary"),
                        ],
                        db_index=True,
                        help_text="Canonical field of study, normalised from the department name.",
                        max_length=30,
                    ),
                ),
                (
                    "department_raw",
                    models.CharField(
                        blank=True,
                        help_text="Original department/faculty name as recorded.",
                        max_length=150,
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Enrollment batch/year, e.g. '078'.",
                        max_length=8,
                    ),
                ),
                ("class_roll_no", models.CharField(blank=True, max_length=30)),
                (
                    "current_city",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "current_country",
                    django_countries.fields.CountryField(
                        blank=True, db_index=True, max_length=2
                    ),
                ),
                ("permanent_district", models.CharField(blank=True, max_length=100)),
                (
                    "permanent_country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Employed", "Employed"),
                            ("Unemployed", "Unemployed"),
                            ("Studying", "Studying"),
                            ("Retired", "Retired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employer_organization",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Organization the alumnus currently works at.",
                        max_length=150,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=150)),
                (
                    "further_study_institution",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "further_study_country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("contact_number", models.CharField(blank=True, max_length=30)),
                ("linkedin_url", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="If off, the record is hidden from the public directory.",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="The signed-in account that has claimed this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumnus_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "alumni",
                "ordering": ["batch", "last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["batch", "field_of_study"],
                        name="directory_a_batch_a5221b_idx",
                    ),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="directory_a_last_na_b81dde_idx",
                    ),
                ],
            },
        ),
    ]
