# Generated by Django 4.2.14 on 2026-07-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='further_study_degree',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
