# Generated by Django 4.2.14 on 2026-08-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_publish_approved_alumni'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='EventRegistration'),
                migrations.DeleteModel(name='MentorshipRequest'),
                migrations.DeleteModel(name='MentorshipProfile'),
                migrations.DeleteModel(name='AlumniEvent'),
            ],
            database_operations=[],
        ),
    ]
